mkdir -p 鸭科/栗树鸭
mkdir -p 鸭科/黑雁
mkdir -p 鸭科/红胸黑雁
mkdir -p 鸭科/加拿大黑雁
mkdir -p 鸭科/白颊黑雁
mkdir -p 鸭科/小美洲黑雁
mkdir -p 鸭科/斑头雁
mkdir -p 鸭科/雪雁
mkdir -p 鸭科/灰雁
mkdir -p 鸭科/鸿雁
mkdir -p 鸭科/豆雁
mkdir -p 鸭科/短嘴豆雁
mkdir -p 鸭科/白额雁
mkdir -p 鸭科/小白额雁
mkdir -p 鸭科/疣鼻天鹅
mkdir -p 鸭科/小天鹅
mkdir -p 鸭科/大天鹅
mkdir -p 鸭科/瘤鸭
mkdir -p 鸭科/翘鼻麻鸭
mkdir -p 鸭科/赤麻鸭
mkdir -p 鸭科/冠麻鸭
mkdir -p 鸭科/白翅栖鸭
mkdir -p 鸭科/鸳鸯
mkdir -p 鸭科/棉凫
mkdir -p 鸭科/花脸鸭
mkdir -p 鸭科/白眉鸭
mkdir -p 鸭科/琵嘴鸭
mkdir -p 鸭科/赤膀鸭
mkdir -p 鸭科/罗纹鸭
mkdir -p 鸭科/赤颈鸭
mkdir -p 鸭科/绿眉鸭
mkdir -p 鸭科/棕颈鸭
mkdir -p 鸭科/印缅斑嘴鸭
mkdir -p 鸭科/斑嘴鸭
mkdir -p 鸭科/绿头鸭
mkdir -p 鸭科/针尾鸭
mkdir -p 鸭科/绿翅鸭
mkdir -p 鸭科/美洲绿翅鸭
mkdir -p 鸭科/云石斑鸭
mkdir -p 鸭科/赤嘴潜鸭
mkdir -p 鸭科/帆背潜鸭
mkdir -p 鸭科/红头潜鸭
mkdir -p 鸭科/青头潜鸭
mkdir -p 鸭科/白眼潜鸭
mkdir -p 鸭科/环颈潜鸭
mkdir -p 鸭科/凤头潜鸭
mkdir -p 鸭科/斑背潜鸭
mkdir -p 鸭科/小潜鸭
mkdir -p 鸭科/小绒鸭
mkdir -p 鸭科/丑鸭
mkdir -p 鸭科/丝绒海番鸭
mkdir -p 鸭科/斑脸海番鸭
mkdir -p 鸭科/黑海番鸭
mkdir -p 鸭科/长尾鸭
mkdir -p 鸭科/鹊鸭
mkdir -p 鸭科/斑头秋沙鸭
mkdir -p 鸭科/普通秋沙鸭
mkdir -p 鸭科/红胸秋沙鸭
mkdir -p 鸭科/中华秋沙鸭
mkdir -p 鸭科/白头硬尾鸭
mkdir -p 雉科/环颈山鹧鸪
mkdir -p 雉科/四川山鹧鸪
mkdir -p 雉科/红胸山鹧鸪
mkdir -p 雉科/白眉山鹧鸪
mkdir -p 雉科/红喉山鹧鸪
mkdir -p 雉科/海南山鹧鸪
mkdir -p 雉科/台湾山鹧鸪
mkdir -p 雉科/白颊山鹧鸪
mkdir -p 雉科/褐胸山鹧鸪
mkdir -p 雉科/雪鹑
mkdir -p 雉科/血雉
mkdir -p 雉科/黑头角雉
mkdir -p 雉科/红胸角雉
mkdir -p 雉科/灰腹角雉
mkdir -p 雉科/红腹角雉
mkdir -p 雉科/黄腹角雉
mkdir -p 雉科/红喉雉鹑
mkdir -p 雉科/黄喉雉鹑
mkdir -p 雉科/棕尾虹雉
mkdir -p 雉科/白尾梢虹雉
mkdir -p 雉科/绿尾虹雉
mkdir -p 雉科/勺鸡
mkdir -p 雉科/花尾榛鸡
mkdir -p 雉科/斑尾榛鸡
mkdir -p 雉科/柳雷鸟
mkdir -p 雉科/岩雷鸟
mkdir -p 雉科/镰翅鸡
mkdir -p 雉科/西方松鸡
mkdir -p 雉科/黑嘴松鸡
mkdir -p 雉科/黑琴鸡
mkdir -p 雉科/高原山鹑
mkdir -p 雉科/灰山鹑
mkdir -p 雉科/斑翅山鹑
mkdir -p 雉科/白冠长尾雉
mkdir -p 雉科/黑长尾雉
mkdir -p 雉科/白颈长尾雉
mkdir -p 雉科/黑颈长尾雉
mkdir -p 雉科/红腹锦鸡
mkdir -p 雉科/白腹锦鸡
mkdir -p 雉科/雉鸡
mkdir -p 雉科/藏马鸡
mkdir -p 雉科/白马鸡
mkdir -p 雉科/褐马鸡
mkdir -p 雉科/蓝马鸡
mkdir -p 雉科/蓝腹鹇
mkdir -p 雉科/黑鹇
mkdir -p 雉科/白鹇
mkdir -p 雉科/绿孔雀
mkdir -p 雉科/绿脚树鹧鸪
mkdir -p 雉科/海南孔雀雉
mkdir -p 雉科/灰孔雀雉
mkdir -p 雉科/棕胸竹鸡
mkdir -p 雉科/灰胸竹鸡
mkdir -p 雉科/台湾竹鸡
mkdir -p 雉科/红原鸡
mkdir -p 雉科/中华鹧鸪
mkdir -p 雉科/藏雪鸡
mkdir -p 雉科/阿尔泰雪鸡
mkdir -p 雉科/暗腹雪鸡
mkdir -p 雉科/蓝胸鹑
mkdir -p 雉科/西鹌鹑
mkdir -p 雉科/鹌鹑
mkdir -p 雉科/石鸡
mkdir -p 雉科/大石鸡
mkdir -p 潜鸟科/红喉潜鸟
mkdir -p 潜鸟科/黑喉潜鸟
mkdir -p 潜鸟科/太平洋潜鸟
mkdir -p 潜鸟科/黄嘴潜鸟
mkdir -p 洋海燕科/黄蹼洋海燕
mkdir -p 信天翁科/黑背信天翁
mkdir -p 信天翁科/黑脚信天翁
mkdir -p 信天翁科/短尾信天翁
mkdir -p 海燕科/黑叉尾海燕
mkdir -p 海燕科/白腰叉尾海燕
mkdir -p 海燕科/褐翅叉尾海燕
mkdir -p 海燕科/日本叉尾海燕
mkdir -p 鹱科/暴雪鹱
mkdir -p 鹱科/棕头圆尾鹱
mkdir -p 鹱科/信使圆尾鹱
mkdir -p 鹱科/白额圆尾鹱
mkdir -p 鹱科/钩嘴圆尾鹱
mkdir -p 鹱科/白额鹱
mkdir -p 鹱科/楔尾鹱
mkdir -p 鹱科/灰鹱
mkdir -p 鹱科/短尾鹱
mkdir -p 鹱科/淡足鹱
mkdir -p 鹱科/褐燕鹱
mkdir -p 䴙䴘科/小䴙䴘
mkdir -p 䴙䴘科/赤颈䴙䴘
mkdir -p 䴙䴘科/凤头䴙䴘
mkdir -p 䴙䴘科/角䴙䴘
mkdir -p 䴙䴘科/黑颈䴙䴘
mkdir -p 红鹳科/大红鹳
mkdir -p 鹲科/红嘴鹲
mkdir -p 鹲科/红尾鹲
mkdir -p 鹲科/白尾鹲
mkdir -p 鹳科/彩鹳
mkdir -p 鹳科/钳嘴鹳
mkdir -p 鹳科/黑鹳
mkdir -p 鹳科/白颈鹳
mkdir -p 鹳科/白鹳
mkdir -p 鹳科/东方白鹳
mkdir -p 鹳科/秃鹳
mkdir -p 鹮科/黑头白鹮
mkdir -p 鹮科/白肩黑鹮
mkdir -p 鹮科/朱鹮
mkdir -p 鹮科/彩鹮
mkdir -p 鹮科/白琵鹭
mkdir -p 鹮科/黑脸琵鹭
mkdir -p 鹭科/大麻鳽
mkdir -p 鹭科/小苇鳽
mkdir -p 鹭科/黄苇鳽
mkdir -p 鹭科/紫背苇鳽
mkdir -p 鹭科/栗苇鳽
mkdir -p 鹭科/黑鳽
mkdir -p 鹭科/海南鳽
mkdir -p 鹭科/栗鳽
mkdir -p 鹭科/黑冠鳽
mkdir -p 鹭科/夜鹭
mkdir -p 鹭科/棕夜鹭
mkdir -p 鹭科/绿鹭
mkdir -p 鹭科/印度池鹭
mkdir -p 鹭科/池鹭
mkdir -p 鹭科/爪哇池鹭
mkdir -p 鹭科/牛背鹭
mkdir -p 鹭科/苍鹭
mkdir -p 鹭科/白腹鹭
mkdir -p 鹭科/草鹭
mkdir -p 鹭科/大白鹭
mkdir -p 鹭科/中白鹭
mkdir -p 鹭科/斑鹭
mkdir -p 鹭科/白脸鹭
mkdir -p 鹭科/白鹭
mkdir -p 鹭科/岩鹭
mkdir -p 鹭科/黄嘴白鹭
mkdir -p 鹈鹕科/白鹈鹕
mkdir -p 鹈鹕科/斑嘴鹈鹕
mkdir -p 鹈鹕科/卷羽鹈鹕
mkdir -p 军舰鸟科/白腹军舰鸟
mkdir -p 军舰鸟科/黑腹军舰鸟
mkdir -p 军舰鸟科/白斑军舰鸟
mkdir -p 鲣鸟科/蓝脸鲣鸟
mkdir -p 鲣鸟科/红脚鲣鸟
mkdir -p 鲣鸟科/褐鲣鸟
mkdir -p 蛇鹈科/黑腹蛇鹈
mkdir -p 鸬鹚科/侏鸬鹚
mkdir -p 鸬鹚科/黑颈鸬鹚
mkdir -p 鸬鹚科/红脸鸬鹚
mkdir -p 鸬鹚科/海鸬鹚
mkdir -p 鸬鹚科/暗绿背鸬鹚
mkdir -p 鸬鹚科/普通鸬鹚
mkdir -p 鹗科/鹗
mkdir -p 鹰科/黑翅鸢
mkdir -p 鹰科/胡兀鹫
mkdir -p 鹰科/白兀鹫
mkdir -p 鹰科/鹃头蜂鹰
mkdir -p 鹰科/凤头蜂鹰
mkdir -p 鹰科/褐冠鹃隼
mkdir -p 鹰科/黑冠鹃隼
mkdir -p 鹰科/白背兀鹫
mkdir -p 鹰科/细嘴兀鹫
mkdir -p 鹰科/高山兀鹫
mkdir -p 鹰科/兀鹫
mkdir -p 鹰科/黑兀鹫
mkdir -p 鹰科/秃鹫
mkdir -p 鹰科/蛇雕
mkdir -p 鹰科/短趾雕
mkdir -p 鹰科/凤头鹰雕
mkdir -p 鹰科/鹰雕
mkdir -p 鹰科/棕腹隼雕
mkdir -p 鹰科/林雕
mkdir -p 鹰科/乌雕
mkdir -p 鹰科/靴隼雕
mkdir -p 鹰科/草原雕
mkdir -p 鹰科/白肩雕
mkdir -p 鹰科/金雕
mkdir -p 鹰科/白腹隼雕
mkdir -p 鹰科/凤头鹰
mkdir -p 鹰科/褐耳鹰
mkdir -p 鹰科/赤腹鹰
mkdir -p 鹰科/日本松雀鹰
mkdir -p 鹰科/松雀鹰
mkdir -p 鹰科/雀鹰
mkdir -p 鹰科/苍鹰
mkdir -p 鹰科/白头鹞
mkdir -p 鹰科/白腹鹞
mkdir -p 鹰科/白尾鹞
mkdir -p 鹰科/草原鹞
mkdir -p 鹰科/鹊鹞
mkdir -p 鹰科/乌灰鹞
mkdir -p 鹰科/黑鸢
mkdir -p 鹰科/栗鸢
mkdir -p 鹰科/白腹海雕
mkdir -p 鹰科/玉带海雕
mkdir -p 鹰科/白尾海雕
mkdir -p 鹰科/虎头海雕
mkdir -p 鹰科/渔雕
mkdir -p 鹰科/白眼鵟鹰
mkdir -p 鹰科/棕翅鵟鹰
mkdir -p 鹰科/灰脸鵟鹰
mkdir -p 鹰科/毛脚鵟
mkdir -p 鹰科/大鵟
mkdir -p 鹰科/普通鵟
mkdir -p 鹰科/喜山鵟
mkdir -p 鹰科/棕尾鵟
mkdir -p 鹰科/欧亚鵟
mkdir -p 鸨科/大鸨
mkdir -p 鸨科/波斑鸨
mkdir -p 鸨科/小鸨
mkdir -p 秧鸡科/西方秧鸡
mkdir -p 秧鸡科/普通秧鸡
mkdir -p 秧鸡科/长脚秧鸡
mkdir -p 秧鸡科/灰胸秧鸡
mkdir -p 秧鸡科/斑胸田鸡
mkdir -p 秧鸡科/黑水鸡
mkdir -p 秧鸡科/白骨顶
mkdir -p 秧鸡科/紫水鸡
mkdir -p 秧鸡科/黑背紫水鸡
mkdir -p 秧鸡科/花田鸡
mkdir -p 秧鸡科/斑胁田鸡
mkdir -p 秧鸡科/棕背田鸡
mkdir -p 秧鸡科/红脚田鸡
mkdir -p 秧鸡科/小田鸡
mkdir -p 秧鸡科/姬田鸡
mkdir -p 秧鸡科/红胸田鸡
mkdir -p 秧鸡科/白喉斑秧鸡
mkdir -p 秧鸡科/红腿斑秧鸡
mkdir -p 秧鸡科/白眉田鸡
mkdir -p 秧鸡科/董鸡
mkdir -p 秧鸡科/白胸苦恶鸟
mkdir -p 鹤科/白鹤
mkdir -p 鹤科/沙丘鹤
mkdir -p 鹤科/白枕鹤
mkdir -p 鹤科/赤颈鹤
mkdir -p 鹤科/蓑羽鹤
mkdir -p 鹤科/丹顶鹤
mkdir -p 鹤科/灰鹤
mkdir -p 鹤科/白头鹤
mkdir -p 鹤科/黑颈鹤
mkdir -p 三趾鹑科/林三趾鹑
mkdir -p 三趾鹑科/黄脚三趾鹑
mkdir -p 三趾鹑科/棕三趾鹑
mkdir -p 石鸻科/石鸻
mkdir -p 石鸻科/大石鸻
mkdir -p 蛎鹬科/蛎鹬
mkdir -p 鹮嘴鹬科/鹮嘴鹬
mkdir -p 反嘴鹬科/黑翅长脚鹬
mkdir -p 反嘴鹬科/反嘴鹬
mkdir -p 鸻科/凤头麦鸡
mkdir -p 鸻科/距翅麦鸡
mkdir -p 鸻科/灰头麦鸡
mkdir -p 鸻科/肉垂麦鸡
mkdir -p 鸻科/黄颊麦鸡
mkdir -p 鸻科/白尾麦鸡
mkdir -p 鸻科/欧金鸻
mkdir -p 鸻科/金斑鸻
mkdir -p 鸻科/美洲金鸻
mkdir -p 鸻科/灰斑鸻
mkdir -p 鸻科/剑鸻
mkdir -p 鸻科/长嘴剑鸻
mkdir -p 鸻科/金眶鸻
mkdir -p 鸻科/环颈鸻
mkdir -p 鸻科/白脸鸻
mkdir -p 鸻科/蒙古沙鸻
mkdir -p 鸻科/青藏沙鸻
mkdir -p 鸻科/铁嘴沙鸻
mkdir -p 鸻科/红胸鸻
mkdir -p 鸻科/东方鸻
mkdir -p 鸻科/小嘴鸻
mkdir -p 彩鹬科/彩鹬
mkdir -p 水雉科/水雉
mkdir -p 水雉科/铜翅水雉
mkdir -p 丘鹬科/中杓鹬
mkdir -p 丘鹬科/小杓鹬
mkdir -p 丘鹬科/大杓鹬
mkdir -p 丘鹬科/白腰杓鹬
mkdir -p 丘鹬科/斑尾塍鹬
mkdir -p 丘鹬科/黑尾塍鹬
mkdir -p 丘鹬科/翻石鹬
mkdir -p 丘鹬科/大滨鹬
mkdir -p 丘鹬科/红腹滨鹬
mkdir -p 丘鹬科/流苏鹬
mkdir -p 丘鹬科/阔嘴鹬
mkdir -p 丘鹬科/尖尾滨鹬
mkdir -p 丘鹬科/高跷鹬
mkdir -p 丘鹬科/弯嘴滨鹬
mkdir -p 丘鹬科/青脚滨鹬
mkdir -p 丘鹬科/长趾滨鹬
mkdir -p 丘鹬科/勺嘴鹬
mkdir -p 丘鹬科/红颈滨鹬
mkdir -p 丘鹬科/三趾滨鹬
mkdir -p 丘鹬科/黑腹滨鹬
mkdir -p 丘鹬科/岩滨鹬
mkdir -p 黑腰滨鹬/小滨鹬
mkdir -p 黑腰滨鹬/白腰滨鹬
mkdir -p 黑腰滨鹬/黄胸滨鹬
mkdir -p 黑腰滨鹬/斑胸滨鹬
mkdir -p 黑腰滨鹬/西方滨鹬
mkdir -p 黑腰滨鹬/半蹼鹬
mkdir -p 黑腰滨鹬/长嘴半蹼鹬
mkdir -p 黑腰滨鹬/丘鹬
mkdir -p 黑腰滨鹬/姬鹬
mkdir -p 黑腰滨鹬/孤沙锥
mkdir -p 黑腰滨鹬/拉氏沙锥
mkdir -p 黑腰滨鹬/林沙锥
mkdir -p 黑腰滨鹬/针尾沙锥
mkdir -p 黑腰滨鹬/大沙锥
mkdir -p 黑腰滨鹬/扇尾沙锥
mkdir -p 黑腰滨鹬/翘嘴鹬
mkdir -p 黑腰滨鹬/红颈瓣蹼鹬
mkdir -p 黑腰滨鹬/灰瓣蹼鹬
mkdir -p 黑腰滨鹬/矶鹬
mkdir -p 黑腰滨鹬/白腰草鹬
mkdir -p 黑腰滨鹬/漂鹬
mkdir -p 黑腰滨鹬/灰尾漂鹬
mkdir -p 黑腰滨鹬/小黄脚鹬
mkdir -p 黑腰滨鹬/红脚鹬
mkdir -p 黑腰滨鹬/泽鹬
mkdir -p 黑腰滨鹬/林鹬
mkdir -p 黑腰滨鹬/鹤鹬
mkdir -p 黑腰滨鹬/青脚鹬
mkdir -p 黑腰滨鹬/小青脚鹬
mkdir -p 燕鸻科/领燕鸻
mkdir -p 燕鸻科/普通燕鸻
mkdir -p 燕鸻科/黑翅燕鸻
mkdir -p 燕鸻科/灰燕鸻
mkdir -p 鸥科/白顶玄燕鸥
mkdir -p 鸥科/玄燕鸥
mkdir -p 鸥科/白燕鸥
mkdir -p 鸥科/三趾鸥
mkdir -p 鸥科/叉尾鸥
mkdir -p 鸥科/细嘴鸥
mkdir -p 鸥科/澳洲红嘴鸥
mkdir -p 鸥科/棕头鸥
mkdir -p 鸥科/红嘴鸥
mkdir -p 鸥科/黑嘴鸥
mkdir -p 鸥科/小鸥
mkdir -p 鸥科/楔尾鸥
mkdir -p 鸥科/笑鸥
mkdir -p 鸥科/弗氏鸥
mkdir -p 鸥科/遗鸥
mkdir -p 鸥科/渔鸥
mkdir -p 鸥科/黑尾鸥
mkdir -p 鸥科/普通海鸥
mkdir -p 鸥科/美洲海鸥
mkdir -p 鸥科/环嘴鸥
mkdir -p 鸥科/灰翅鸥
mkdir -p 鸥科/北极鸥
mkdir -p 鸥科/西伯利亚银鸥
mkdir -p 鸥科/里海银鸥
mkdir -p 鸥科/灰背鸥
mkdir -p 鸥科/小黑背鸥
mkdir -p 鸥科/鸥嘴噪鸥
mkdir -p 鸥科/红嘴巨燕鸥
mkdir -p 鸥科/大凤头燕鸥
mkdir -p 鸥科/小凤头燕鸥
mkdir -p 鸥科/中华凤头燕鸥
mkdir -p 鸥科/白嘴端凤头燕鸥
mkdir -p 鸥科/白额燕鸥
mkdir -p 鸥科/白腰燕鸥
mkdir -p 鸥科/褐翅燕鸥
mkdir -p 鸥科/乌燕鸥
mkdir -p 鸥科/黄嘴河燕鸥
mkdir -p 鸥科/粉红燕鸥
mkdir -p 鸥科/黑枕燕鸥
mkdir -p 鸥科/普通燕鸥
mkdir -p 鸥科/黑腹燕鸥
mkdir -p 鸥科/须浮鸥
mkdir -p 鸥科/白翅浮鸥
mkdir -p 鸥科/黑浮鸥
mkdir -p 贼鸥科/南极贼鸥
mkdir -p 贼鸥科/中贼鸥
mkdir -p 贼鸥科/短尾贼鸥
mkdir -p 贼鸥科/长尾贼鸥
mkdir -p 海雀科/崖海鸦
mkdir -p 海雀科/长嘴斑海雀
mkdir -p 海雀科/扁嘴海雀
mkdir -p 海雀科/冠海雀
mkdir -p 海雀科/角嘴海雀
mkdir -p 沙鸡科/西藏毛腿沙鸡
mkdir -p 沙鸡科/毛腿沙鸡
mkdir -p 沙鸡科/黑腹沙鸡
mkdir -p 鸠鸽科/原鸽
mkdir -p 鸠鸽科/岩鸽
mkdir -p 鸠鸽科/雪鸽
mkdir -p 鸠鸽科/欧鸽
mkdir -p 鸠鸽科/中亚鸽
mkdir -p 鸠鸽科/斑尾林鸽
mkdir -p 鸠鸽科/点斑林鸽
mkdir -p 鸠鸽科/灰林鸽
mkdir -p 鸠鸽科/紫林鸽
mkdir -p 鸠鸽科/黑林鸽
mkdir -p 鸠鸽科/白喉林鸽
mkdir -p 鸠鸽科/欧斑鸠
mkdir -p 鸠鸽科/山斑鸠
mkdir -p 鸠鸽科/灰斑鸠
mkdir -p 鸠鸽科/火斑鸠
mkdir -p 鸠鸽科/珠颈斑鸠
mkdir -p 鸠鸽科/棕斑鸠
mkdir -p 鸠鸽科/斑尾鹃鸠
mkdir -p 鸠鸽科/菲律宾鹃鸠
mkdir -p 鸠鸽科/小鹃鸠
mkdir -p 鸠鸽科/绿翅金鸠
mkdir -p 鸠鸽科/斑姬地鸠
mkdir -p 鸠鸽科/橙胸绿鸠
mkdir -p 鸠鸽科/灰头绿鸠
mkdir -p 鸠鸽科/厚嘴绿鸠
mkdir -p 鸠鸽科/黄脚绿鸠
mkdir -p 鸠鸽科/针尾绿鸠
mkdir -p 鸠鸽科/白腹针尾绿鸠
mkdir -p 鸠鸽科/楔尾绿鸠
mkdir -p 鸠鸽科/红翅绿鸠
mkdir -p 鸠鸽科/红顶绿鸠
mkdir -p 鸠鸽科/黑颏果鸠
mkdir -p 鸠鸽科/绿皇鸠
mkdir -p 鸠鸽科/山皇鸠
mkdir -p 杜鹃科/褐翅鸦鹃
mkdir -p 杜鹃科/小鸦鹃
mkdir -p 杜鹃科/绿嘴地鹃
mkdir -p 杜鹃科/红翅凤头鹃
mkdir -p 杜鹃科/斑翅凤头鹃
mkdir -p 杜鹃科/噪鹃
mkdir -p 杜鹃科/翠金鹃
mkdir -p 杜鹃科/紫金鹃
mkdir -p 杜鹃科/栗斑杜鹃
mkdir -p 杜鹃科/八声杜鹃
mkdir -p 杜鹃科/乌鹃
mkdir -p 杜鹃科/大鹰鹃
mkdir -p 杜鹃科/普通鹰鹃
mkdir -p 杜鹃科/北棕腹鹰鹃
mkdir -p 杜鹃科/棕腹鹰鹃
mkdir -p 杜鹃科/小杜鹃
mkdir -p 杜鹃科/四声杜鹃
mkdir -p 杜鹃科/中杜鹃
mkdir -p 杜鹃科/东方中杜鹃
mkdir -p 杜鹃科/大杜鹃
mkdir -p 仓鸮科/仓鸮
mkdir -p 仓鸮科/草鸮
mkdir -p 仓鸮科/栗鸮
mkdir -p 鸱鸮科/北鹰鸮
mkdir -p 鸱鸮科/鹰鸮
mkdir -p 鸱鸮科/领鸺鹠
mkdir -p 鸱鸮科/鬼鸮
mkdir -p 鸱鸮科/横斑腹小鸮
mkdir -p 鸱鸮科/纵纹腹小鸮
mkdir -p 鸱鸮科/猛鸮
mkdir -p 鸱鸮科/花头鸺鹠
mkdir -p 鸱鸮科/斑头鸺鹠
mkdir -p 鸱鸮科/黄嘴角鸮
mkdir -p 鸱鸮科/西红角鸮
mkdir -p 鸱鸮科/纵纹角鸮
mkdir -p 鸱鸮科/红角鸮
mkdir -p 鸱鸮科/琉球角鸮
mkdir -p 鸱鸮科/领角鸮
mkdir -p 鸱鸮科/北领角鸮
mkdir -p 鸱鸮科/长耳鸮
mkdir -p 鸱鸮科/短耳鸮
mkdir -p 鸱鸮科/雪鸮
mkdir -p 鸱鸮科/雕鸮
mkdir -p 鸱鸮科/林雕鸮
mkdir -p 鸱鸮科/乌雕鸮
mkdir -p 鸱鸮科/毛腿雕鸮
mkdir -p 鸱鸮科/褐渔鸮
mkdir -p 鸱鸮科/黄腿渔鸮
mkdir -p 鸱鸮科/褐林鸮
mkdir -p 鸱鸮科/灰林鸮
mkdir -p 鸱鸮科/长尾林鸮
mkdir -p 鸱鸮科/乌林鸮
mkdir -p 蟆口鸱科/黑顶蟆口鸱
mkdir -p 夜鹰科/毛腿耳夜鹰
mkdir -p 夜鹰科/普通夜鹰
mkdir -p 夜鹰科/欧夜鹰
mkdir -p 夜鹰科/埃及夜鹰
mkdir -p 夜鹰科/长尾夜鹰
mkdir -p 夜鹰科/林夜鹰
mkdir -p 树燕科/凤头雨燕
mkdir -p 雨燕科/短嘴金丝燕
mkdir -p 雨燕科/戈氏金丝燕
mkdir -p 雨燕科/白喉针尾雨燕
mkdir -p 雨燕科/灰喉针尾雨燕
mkdir -p 雨燕科/褐背针尾雨燕
mkdir -p 雨燕科/紫针尾雨燕
mkdir -p 雨燕科/棕雨燕
mkdir -p 雨燕科/高山雨燕
mkdir -p 雨燕科/普通雨燕
mkdir -p 雨燕科/白腰雨燕
mkdir -p 雨燕科/华西白腰雨燕
mkdir -p 雨燕科/印支白腰雨燕
mkdir -p 雨燕科/暗背雨燕
mkdir -p 雨燕科/小白腰雨燕
mkdir -p 咬鹃科/橙胸咬鹃
mkdir -p 咬鹃科/红头咬鹃
mkdir -p 咬鹃科/红腹咬鹃
mkdir -p 佛法僧科/棕胸佛法僧
mkdir -p 佛法僧科/蓝胸佛法僧
mkdir -p 佛法僧科/三宝鸟
mkdir -p 翠鸟科/鹳嘴翡翠
mkdir -p 翠鸟科/赤翡翠
mkdir -p 翠鸟科/白胸翡翠
mkdir -p 翠鸟科/蓝翡翠
mkdir -p 翠鸟科/白领翡翠
mkdir -p 翠鸟科/蓝耳翠鸟
mkdir -p 翠鸟科/普通翠鸟
mkdir -p 翠鸟科/斑头大翠鸟
mkdir -p 翠鸟科/三趾翠鸟
mkdir -p 翠鸟科/冠鱼狗
mkdir -p 翠鸟科/斑鱼狗
mkdir -p 蜂虎科/蓝须夜蜂虎
mkdir -p 蜂虎科/绿喉蜂虎
mkdir -p 蜂虎科/蓝颊蜂虎
mkdir -p 蜂虎科/栗喉蜂虎
mkdir -p 蜂虎科/彩虹蜂虎
mkdir -p 蜂虎科/蓝喉蜂虎
mkdir -p 蜂虎科/栗头蜂虎
mkdir -p 蜂虎科/黄喉蜂虎
mkdir -p 戴胜科/戴胜
mkdir -p 犀鸟科/双角犀鸟
mkdir -p 犀鸟科/冠斑犀鸟
mkdir -p 犀鸟科/白喉犀鸟
mkdir -p 犀鸟科/棕颈犀鸟
mkdir -p 犀鸟科/花冠皱盔犀鸟
mkdir -p 拟啄木鸟科/大拟啄木鸟
mkdir -p 拟啄木鸟科/斑头绿拟啄木鸟
mkdir -p 拟啄木鸟科/黄纹拟啄木鸟
mkdir -p 拟啄木鸟科/金喉拟啄木鸟
mkdir -p 拟啄木鸟科/黑眉拟啄木鸟
mkdir -p 拟啄木鸟科/台湾拟啄木鸟
mkdir -p 拟啄木鸟科/蓝喉拟啄木鸟
mkdir -p 拟啄木鸟科/蓝耳拟啄木鸟
mkdir -p 拟啄木鸟科/赤胸拟啄木鸟
mkdir -p 响蜜鴷科/黄腰响蜜䴕
mkdir -p 啄木鸟科/蚁䴕
mkdir -p 啄木鸟科/斑姬啄木鸟
mkdir -p 啄木鸟科/白眉棕啄木鸟
mkdir -p 啄木鸟科/星头啄木鸟
mkdir -p 啄木鸟科/小星头啄木鸟
mkdir -p 啄木鸟科/三趾啄木鸟
mkdir -p 啄木鸟科/褐额啄木鸟
mkdir -p 啄木鸟科/赤胸啄木鸟
mkdir -p 啄木鸟科/小斑啄木鸟
mkdir -p 啄木鸟科/棕腹啄木鸟
mkdir -p 啄木鸟科/茶胸斑啄木鸟
mkdir -p 啄木鸟科/纹胸啄木鸟
mkdir -p 啄木鸟科/黄颈啄木鸟
mkdir -p 啄木鸟科/白翅啄木鸟
mkdir -p 啄木鸟科/大斑啄木鸟
mkdir -p 啄木鸟科/白背啄木鸟
mkdir -p 啄木鸟科/白腹黑啄木鸟
mkdir -p 啄木鸟科/黑啄木鸟
mkdir -p 啄木鸟科/大黄冠啄木鸟
mkdir -p 啄木鸟科/黄冠啄木鸟
mkdir -p 啄木鸟科/花腹绿啄木鸟
mkdir -p 啄木鸟科/鳞喉绿啄木鸟
mkdir -p 啄木鸟科/鳞腹绿啄木鸟
mkdir -p 啄木鸟科/红颈绿啄木鸟
mkdir -p 啄木鸟科/灰头绿啄木鸟
mkdir -p 啄木鸟科/金背三趾啄木鸟
mkdir -p 啄木鸟科/大金背啄木鸟
mkdir -p 啄木鸟科/竹啄木鸟
mkdir -p 啄木鸟科/黄嘴栗啄木鸟
mkdir -p 啄木鸟科/栗啄木鸟
mkdir -p 啄木鸟科/大灰啄木鸟
mkdir -p 隼科/红腿小隼
mkdir -p 隼科/白腿小隼
mkdir -p 隼科/黄爪隼
mkdir -p 隼科/红隼
mkdir -p 隼科/西红脚隼
mkdir -p 隼科/红脚隼
mkdir -p 隼科/灰背隼
mkdir -p 隼科/燕隼
mkdir -p 隼科/猛隼
mkdir -p 隼科/猎隼
mkdir -p 隼科/矛隼
mkdir -p 隼科/游隼
mkdir -p 鹦鹉科/蓝腰鹦鹉
mkdir -p 鹦鹉科/灰头鹦鹉
mkdir -p 鹦鹉科/青头鹦鹉
mkdir -p 鹦鹉科/花头鹦鹉
mkdir -p 鹦鹉科/绯胸鹦鹉
mkdir -p 鹦鹉科/大紫胸鹦鹉
mkdir -p 鹦鹉科/亚历山大鹦鹉
mkdir -p 鹦鹉科/红领绿鹦鹉
mkdir -p 鹦鹉科/短尾鹦鹉
mkdir -p 阔嘴鸟科/长尾阔嘴鸟
mkdir -p 阔嘴鸟科/银胸丝冠鸟
mkdir -p 八色鸫科/双辫八色鸫
mkdir -p 八色鸫科/蓝枕八色鸫
mkdir -p 八色鸫科/蓝背八色鸫
mkdir -p 八色鸫科/栗头八色鸫
mkdir -p 八色鸫科/蓝八色鸫
mkdir -p 八色鸫科/绿胸八色鸫
mkdir -p 八色鸫科/仙八色鸫
mkdir -p 八色鸫科/蓝翅八色鸫
mkdir -p 钩嘴鵙科/褐背鹟鵙
mkdir -p 钩嘴鵙科/钩嘴林鵙
mkdir -p 燕鵙科/灰燕鵙
mkdir -p 雀鹎科/黑翅雀鹎
mkdir -p 雀鹎科/大绿雀鹎
mkdir -p 鹃鵙科/灰喉山椒鸟
mkdir -p 鹃鵙科/短嘴山椒鸟
mkdir -p 鹃鵙科/长尾山椒鸟
mkdir -p 鹃鵙科/赤红山椒鸟
mkdir -p 鹃鵙科/灰山椒鸟
mkdir -p 鹃鵙科/琉球山椒鸟
mkdir -p 鹃鵙科/小灰山椒鸟
mkdir -p 鹃鵙科/粉红山椒鸟
mkdir -p 鹃鵙科/大鹃鵙
mkdir -p 鹃鵙科/黑鸣鹃鵙
mkdir -p 鹃鵙科/暗灰鹃鵙
mkdir -p 伯劳科/虎纹伯劳
mkdir -p 伯劳科/牛头伯劳
mkdir -p 伯劳科/红尾伯劳
mkdir -p 伯劳科/红背伯劳
mkdir -p 伯劳科/荒漠伯劳
mkdir -p 伯劳科/棕尾伯劳
mkdir -p 伯劳科/栗背伯劳
mkdir -p 伯劳科/褐背伯劳
mkdir -p 伯劳科/棕背伯劳
mkdir -p 伯劳科/灰背伯劳
mkdir -p 伯劳科/黑额伯劳
mkdir -p 伯劳科/灰伯劳
mkdir -p 伯劳科/西方灰伯劳
mkdir -p 伯劳科/青藏楔尾伯劳
mkdir -p 伯劳科/楔尾伯劳
mkdir -p 莺雀科/淡绿鵙鹛
mkdir -p 莺雀科/栗喉鵙鹛
mkdir -p 莺雀科/棕腹鵙鹛
mkdir -p 莺雀科/红翅鵙鹛
mkdir -p 莺雀科/栗额鵙鹛
mkdir -p 莺雀科/白腹凤鹛
mkdir -p 黄鹂科/朱鹂
mkdir -p 黄鹂科/鹊色鹂
mkdir -p 黄鹂科/黑头黄鹂
mkdir -p 黄鹂科/印度金黄鹂
mkdir -p 黄鹂科/金黄鹂
mkdir -p 黄鹂科/黑枕黄鹂
mkdir -p 黄鹂科/细嘴黄鹂
mkdir -p 卷尾科/古铜色卷尾
mkdir -p 卷尾科/小盘尾
mkdir -p 卷尾科/鸦嘴卷尾
mkdir -p 卷尾科/大盘尾
mkdir -p 卷尾科/发冠卷尾
mkdir -p 卷尾科/灰卷尾
mkdir -p 卷尾科/黑卷尾
mkdir -p 扇尾鹟科/白喉扇尾鹟
mkdir -p 扇尾鹟科/白眉扇尾鹟
mkdir -p 扇尾鹟科/菲律宾斑扇尾鹟
mkdir -p 王鹟科/黑枕王鹟
mkdir -p 王鹟科/印度寿带
mkdir -p 王鹟科/中南寿带
mkdir -p 王鹟科/寿带
mkdir -p 王鹟科/紫寿带
mkdir -p 鸦科/北噪鸦
mkdir -p 鸦科/黑头噪鸦
mkdir -p 鸦科/松鸦
mkdir -p 鸦科/灰喜鹊
mkdir -p 鸦科/台湾蓝鹊
mkdir -p 鸦科/黄嘴蓝鹊
mkdir -p 鸦科/红嘴蓝鹊
mkdir -p 鸦科/白翅蓝鹊
mkdir -p 鸦科/蓝绿鹊
mkdir -p 鸦科/印支绿鹊
mkdir -p 鸦科/棕腹树鹊
mkdir -p 鸦科/灰树鹊
mkdir -p 鸦科/黑额树鹊
mkdir -p 鸦科/塔尾树鹊
mkdir -p 鸦科/欧亚喜鹊
mkdir -p 鸦科/青藏喜鹊
mkdir -p 鸦科/喜鹊
mkdir -p 鸦科/黑尾地鸦
mkdir -p 鸦科/白尾地鸦
mkdir -p 鸦科/星鸦
mkdir -p 鸦科/大斑星鸦
mkdir -p 鸦科/红嘴山鸦
mkdir -p 鸦科/黄嘴山鸦
mkdir -p 鸦科/寒鸦
mkdir -p 鸦科/达乌里寒鸦
mkdir -p 鸦科/家鸦
mkdir -p 鸦科/秃鼻乌鸦
mkdir -p 鸦科/小嘴乌鸦
mkdir -p 鸦科/冠小嘴乌鸦
mkdir -p 鸦科/白颈鸦
mkdir -p 鸦科/大嘴乌鸦
mkdir -p 鸦科/丛林鸦
mkdir -p 鸦科/渡鸦
mkdir -p 太平鸟科/太平鸟
mkdir -p 太平鸟科/小太平鸟
mkdir -p 仙莺科/黄腹扇尾鹟
mkdir -p 仙莺科/方尾鹟
mkdir -p 山雀科/火冠雀
mkdir -p 山雀科/黄眉林雀
mkdir -p 山雀科/冕雀
mkdir -p 山雀科/棕枕山雀
mkdir -p 山雀科/黑冠山雀
mkdir -p 山雀科/煤山雀
mkdir -p 山雀科/黄腹山雀
mkdir -p 山雀科/褐冠山雀
mkdir -p 山雀科/杂色山雀
mkdir -p 山雀科/台湾杂色山雀
mkdir -p 山雀科/白眉山雀
mkdir -p 山雀科/红腹山雀
mkdir -p 山雀科/沼泽山雀
mkdir -p 山雀科/黑喉山雀
mkdir -p 山雀科/褐头山雀
mkdir -p 山雀科/川褐头山雀
mkdir -p 山雀科/灰蓝山雀
mkdir -p 山雀科/地山雀
mkdir -p 山雀科/欧亚大山雀
mkdir -p 山雀科/大山雀
mkdir -p 山雀科/苍背山雀
mkdir -p 山雀科/绿背山雀
mkdir -p 山雀科/台湾黄山雀
mkdir -p 山雀科/眼纹黄山雀
mkdir -p 山雀科/黄颊山雀
mkdir -p 攀雀科/白冠攀雀
mkdir -p 攀雀科/中华攀雀
mkdir -p 文须雀科/文须雀
mkdir -p 百灵科/歌百灵
mkdir -p 百灵科/白翅云雀
mkdir -p 百灵科/小云雀
mkdir -p 百灵科/云雀
mkdir -p 百灵科/日本云雀
mkdir -p 百灵科/凤头百灵
mkdir -p 百灵科/角百灵
mkdir -p 百灵科/细嘴短趾百灵
mkdir -p 百灵科/蒙古短趾百灵
mkdir -p 百灵科/大短趾百灵
mkdir -p 百灵科/双斑百灵
mkdir -p 百灵科/草原百灵
mkdir -p 百灵科/黑百灵
mkdir -p 百灵科/蒙古百灵
mkdir -p 百灵科/长嘴百灵
mkdir -p 百灵科/亚洲短趾百灵
mkdir -p 百灵科/中亚短趾百灵
mkdir -p 鹎科/黄腹冠鹎
mkdir -p 鹎科/白喉冠鹎
mkdir -p 鹎科/纵纹绿鹎
mkdir -p 鹎科/灰眼短脚鹎
mkdir -p 鹎科/灰短脚鹎
mkdir -p 鹎科/栗背短脚鹎
mkdir -p 鹎科/绿翅短脚鹎
mkdir -p 鹎科/栗耳短脚鹎
mkdir -p 鹎科/黑短脚鹎
mkdir -p 鹎科/黑头鹎
mkdir -p 鹎科/黑冠黄鹎
mkdir -p 鹎科/凤头雀嘴鹎
mkdir -p 鹎科/领雀嘴鹎
mkdir -p 鹎科/纹喉鹎
mkdir -p 鹎科/黄绿鹎
mkdir -p 鹎科/黄臀鹎
mkdir -p 鹎科/白头鹎
mkdir -p 鹎科/台湾鹎
mkdir -p 鹎科/红耳鹎
mkdir -p 鹎科/白眉黄臀鹎
mkdir -p 鹎科/黑喉红臀鹎
mkdir -p 鹎科/白喉红臀鹎
mkdir -p 鹎科/白颊鹎
mkdir -p 燕科/崖沙燕
mkdir -p 燕科/淡色沙燕
mkdir -p 燕科/灰喉沙燕
mkdir -p 燕科/岩燕
mkdir -p 燕科/纯色岩燕
mkdir -p 燕科/洋燕
mkdir -p 燕科/线尾燕
mkdir -p 燕科/家燕
mkdir -p 燕科/西方毛脚燕
mkdir -p 燕科/白腹毛脚燕
mkdir -p 燕科/烟腹毛脚燕
mkdir -p 燕科/黑喉毛脚燕
mkdir -p 燕科/金腰燕
mkdir -p 燕科/斑腰燕
mkdir -p 燕科/黄额燕
mkdir -p 鳞胸鹪鹛科/鳞胸鹪鹛
mkdir -p 鳞胸鹪鹛科/台湾鹪鹛
mkdir -p 鳞胸鹪鹛科/尼泊尔鹪鹛
mkdir -p 鳞胸鹪鹛科/小鳞胸鹪鹛
mkdir -p 树莺科/黄腹鹟莺
mkdir -p 树莺科/棕脸鹟莺
mkdir -p 树莺科/黑脸鹟莺
mkdir -p 树莺科/金头拟缝叶莺
mkdir -p 树莺科/宽嘴鹟莺
mkdir -p 树莺科/日本树莺
mkdir -p 树莺科/远东树莺
mkdir -p 树莺科/强脚树莺
mkdir -p 树莺科/喜山黄腹树莺
mkdir -p 树莺科/黄腹树莺
mkdir -p 树莺科/异色树莺
mkdir -p 树莺科/灰腹地莺
mkdir -p 树莺科/金冠地莺
mkdir -p 树莺科/宽尾树莺
mkdir -p 树莺科/大树莺
mkdir -p 树莺科/棕顶树莺
mkdir -p 树莺科/栗头地莺
mkdir -p 树莺科/鳞头树莺
mkdir -p 树莺科/淡脚树莺
mkdir -p 长尾山雀科/花彩雀莺
mkdir -p 长尾山雀科/凤头雀莺
mkdir -p 长尾山雀科/北长尾山雀
mkdir -p 长尾山雀科/银喉长尾山雀
mkdir -p 长尾山雀科/红头长尾山雀
mkdir -p 长尾山雀科/棕额长尾山雀
mkdir -p 长尾山雀科/黑眉长尾山雀
mkdir -p 长尾山雀科/银脸长尾山雀
mkdir -p 柳莺科/林柳莺
mkdir -p 柳莺科/橙斑翅柳莺
mkdir -p 柳莺科/灰喉柳莺
mkdir -p 柳莺科/淡眉柳莺
mkdir -p 柳莺科/黄眉柳莺
mkdir -p 柳莺科/云南柳莺
mkdir -p 柳莺科/淡黄腰柳莺
mkdir -p 柳莺科/四川柳莺
mkdir -p 柳莺科/甘肃柳莺
mkdir -p 柳莺科/黄腰柳莺
mkdir -p 柳莺科/棕眉柳莺
mkdir -p 柳莺科/巨嘴柳莺
mkdir -p 柳莺科/灰柳莺
mkdir -p 柳莺科/黄腹柳莺
mkdir -p 柳莺科/华西柳莺
mkdir -p 柳莺科/烟柳莺
mkdir -p 柳莺科/褐柳莺
mkdir -p 柳莺科/棕腹柳莺
mkdir -p 柳莺科/欧柳莺
mkdir -p 柳莺科/东方叽喳柳莺
mkdir -p 柳莺科/叽喳柳莺
mkdir -p 柳莺科/冕柳莺
mkdir -p 柳莺科/饭岛柳莺
mkdir -p 柳莺科/白眶鹟莺
mkdir -p 柳莺科/灰脸鹟莺
mkdir -p 柳莺科/金眶鹟莺
mkdir -p 柳莺科/灰冠鹟莺
mkdir -p 柳莺科/韦氏鹟莺
mkdir -p 柳莺科/比氏鹟莺
mkdir -p 柳莺科/淡尾鹟莺
mkdir -p 柳莺科/峨眉鹟莺
mkdir -p 柳莺科/双斑绿柳莺
mkdir -p 柳莺科/暗绿柳莺
mkdir -p 柳莺科/峨眉柳莺
mkdir -p 柳莺科/乌嘴柳莺
mkdir -p 柳莺科/库页岛柳莺
mkdir -p 柳莺科/淡脚柳莺
mkdir -p 柳莺科/日本柳莺
mkdir -p 柳莺科/堪察加柳莺
mkdir -p 柳莺科/极北柳莺
mkdir -p 柳莺科/栗头鹟莺
mkdir -p 柳莺科/灰岩柳莺
mkdir -p 柳莺科/黑眉柳莺
mkdir -p 柳莺科/黄胸柳莺
mkdir -p 柳莺科/西南冠纹柳莺
mkdir -p 柳莺科/冠纹柳莺
mkdir -p 柳莺科/华南冠纹柳莺
mkdir -p 柳莺科/白斑尾柳莺
mkdir -p 柳莺科/海南柳莺
mkdir -p 柳莺科/云南白斑尾柳莺
mkdir -p 柳莺科/灰头柳莺
mkdir -p 苇莺科/大苇莺
mkdir -p 苇莺科/东方大苇莺
mkdir -p 苇莺科/噪大苇莺
mkdir -p 苇莺科/黑眉苇莺
mkdir -p 苇莺科/须苇莺
mkdir -p 苇莺科/水蒲苇莺
mkdir -p 苇莺科/细纹苇莺
mkdir -p 苇莺科/钝翅苇莺
mkdir -p 苇莺科/远东苇莺
mkdir -p 苇莺科/稻田苇莺
mkdir -p 苇莺科/布氏苇莺
mkdir -p 苇莺科/芦苇莺
mkdir -p 苇莺科/厚嘴苇莺
mkdir -p 苇莺科/靴篱莺
mkdir -p 苇莺科/赛氏篱莺
mkdir -p 苇莺科/草绿篱莺
mkdir -p 蝗莺科/库页岛蝗莺
mkdir -p 蝗莺科/苍眉蝗莺
mkdir -p 蝗莺科/斑背大尾莺
mkdir -p 蝗莺科/小蝗莺
mkdir -p 蝗莺科/东亚蝗莺
mkdir -p 蝗莺科/北蝗莺
mkdir -p 蝗莺科/矛斑蝗莺
mkdir -p 蝗莺科/棕褐短翅蝗莺
mkdir -p 蝗莺科/巨嘴短翅蝗莺
mkdir -p 蝗莺科/黑斑蝗莺
mkdir -p 蝗莺科/中华短翅蝗莺
mkdir -p 蝗莺科/鸲蝗莺
mkdir -p 蝗莺科/北短翅蝗莺
mkdir -p 蝗莺科/斑胸短翅蝗莺
mkdir -p 蝗莺科/台湾短翅蝗莺
mkdir -p 蝗莺科/高山短翅蝗莺
mkdir -p 蝗莺科/四川短翅蝗莺
mkdir -p 蝗莺科/沼泽大尾莺
mkdir -p 扇尾莺科/棕扇尾莺
mkdir -p 扇尾莺科/金头扇尾莺
mkdir -p 扇尾莺科/喜山山鹪莺
mkdir -p 扇尾莺科/山鹪莺
mkdir -p 扇尾莺科/黑胸山鹪莺
mkdir -p 扇尾莺科/黑喉山鹪莺
mkdir -p 扇尾莺科/暗冕山鹪莺
mkdir -p 扇尾莺科/灰胸山鹪莺
mkdir -p 扇尾莺科/黄腹山鹪莺
mkdir -p 扇尾莺科/纯色山鹪莺
mkdir -p 扇尾莺科/长尾缝叶莺
mkdir -p 扇尾莺科/黑喉缝叶莺
mkdir -p 鹛科/红顶鹛
mkdir -p 鹛科/纹胸鹛
mkdir -p 鹛科/金头穗鹛
mkdir -p 鹛科/黑颏穗鹛
mkdir -p 鹛科/红头穗鹛
mkdir -p 鹛科/黄喉穗鹛
mkdir -p 鹛科/锈喉鹩鹛
mkdir -p 鹛科/斑翅鹩鹛
mkdir -p 鹛科/淡喉鹩鹛
mkdir -p 鹛科/灰腹鹩鹛
mkdir -p 鹛科/红嘴钩嘴鹛
mkdir -p 鹛科/棕头钩嘴鹛
mkdir -p 鹛科/剑嘴鹛
mkdir -p 鹛科/棕颈钩嘴鹛
mkdir -p 鹛科/台湾棕颈钩嘴鹛
mkdir -p 鹛科/灰头钩嘴鹛
mkdir -p 鹛科/长嘴钩嘴鹛
mkdir -p 鹛科/锈脸钩嘴鹛
mkdir -p 鹛科/斑胸钩嘴鹛
mkdir -p 鹛科/华南斑胸钩嘴鹛
mkdir -p 鹛科/台湾斑胸钩嘴鹛
mkdir -p 鹛科/黑头穗鹛
mkdir -p 鹛科/弄岗穗鹛
mkdir -p 鹛科/黑胸楔嘴穗鹛
mkdir -p 鹛科/楔嘴穗鹛
mkdir -p 鹛科/斑颈穗鹛
mkdir -p 幽鹛科/中华草鹛
mkdir -p 幽鹛科/白头鵙鹛
mkdir -p 幽鹛科/领鵙鹛
mkdir -p 幽鹛科/黄喉雀鹛
mkdir -p 幽鹛科/栗头雀鹛
mkdir -p 幽鹛科/金额雀鹛
mkdir -p 幽鹛科/棕喉雀鹛
mkdir -p 幽鹛科/褐胁雀鹛
mkdir -p 幽鹛科/褐顶雀鹛
mkdir -p 幽鹛科/棕头幽鹛
mkdir -p 幽鹛科/白腹幽鹛
mkdir -p 幽鹛科/棕胸雅鹛
mkdir -p 幽鹛科/短尾鹪鹛
mkdir -p 幽鹛科/灰岩鹪鹛
mkdir -p 幽鹛科/纹胸鹪鹛
mkdir -p 幽鹛科/长嘴鹩鹛
mkdir -p 幽鹛科/瑙蒙短尾鹛
mkdir -p 雀鹛科/褐脸雀鹛
mkdir -p 雀鹛科/台湾雀鹛
mkdir -p 雀鹛科/灰眶雀鹛
mkdir -p 雀鹛科/云南雀鹛
mkdir -p 雀鹛科/淡眉雀鹛
mkdir -p 雀鹛科/白眶雀鹛
mkdir -p 噪鹛科/条纹噪鹛
mkdir -p 噪鹛科/斑胁姬鹛
mkdir -p 噪鹛科/纯色噪鹛
mkdir -p 噪鹛科/蓝翅噪鹛
mkdir -p 噪鹛科/细纹噪鹛
mkdir -p 噪鹛科/丽星噪鹛
mkdir -p 噪鹛科/杂色噪鹛
mkdir -p 噪鹛科/黑顶噪鹛
mkdir -p 噪鹛科/玉山噪鹛
mkdir -p 噪鹛科/灰腹噪鹛
mkdir -p 噪鹛科/橙翅噪鹛
mkdir -p 噪鹛科/赤尾噪鹛
mkdir -p 噪鹛科/红头噪鹛
mkdir -p 噪鹛科/金翅噪鹛
mkdir -p 噪鹛科/丽色噪鹛
mkdir -p 噪鹛科/银耳噪鹛
mkdir -p 噪鹛科/长尾奇鹛
mkdir -p 噪鹛科/白耳奇鹛
mkdir -p 噪鹛科/黑顶奇鹛
mkdir -p 噪鹛科/丽色奇鹛
mkdir -p 噪鹛科/灰奇鹛
mkdir -p 噪鹛科/黑头奇鹛
mkdir -p 噪鹛科/纹头斑翅鹛
mkdir -p 噪鹛科/台湾斑翅鹛
mkdir -p 噪鹛科/纹胸斑翅鹛
mkdir -p 噪鹛科/灰头斑翅鹛
mkdir -p 噪鹛科/蓝翅希鹛
mkdir -p 噪鹛科/斑喉希鹛
mkdir -p 噪鹛科/锈额斑翅鹛
mkdir -p 噪鹛科/白眶斑翅鹛
mkdir -p 噪鹛科/红嘴相思鸟
mkdir -p 噪鹛科/银耳相思鸟
mkdir -p 噪鹛科/火尾希鹛
mkdir -p 噪鹛科/栗背奇鹛
mkdir -p 噪鹛科/灰胸薮鹛
mkdir -p 噪鹛科/黄痣薮鹛
mkdir -p 噪鹛科/灰头薮鹛
mkdir -p 噪鹛科/红翅薮鹛
mkdir -p 噪鹛科/斑胸噪鹛
mkdir -p 噪鹛科/画眉
mkdir -p 噪鹛科/台湾画眉
mkdir -p 噪鹛科/小黑领噪鹛
mkdir -p 噪鹛科/白冠噪鹛
mkdir -p 噪鹛科/白颈噪鹛
mkdir -p 噪鹛科/褐胸噪鹛
mkdir -p 噪鹛科/栗颊噪鹛
mkdir -p 噪鹛科/黑额山噪鹛
mkdir -p 噪鹛科/棕颏噪鹛
mkdir -p 噪鹛科/灰翅噪鹛
mkdir -p 噪鹛科/眼纹噪鹛
mkdir -p 噪鹛科/大噪鹛
mkdir -p 噪鹛科/白点噪鹛
mkdir -p 噪鹛科/斑背噪鹛
mkdir -p 噪鹛科/棕臀噪鹛
mkdir -p 噪鹛科/黄喉噪鹛
mkdir -p 噪鹛科/靛冠噪鹛
mkdir -p 噪鹛科/栗颈噪鹛
mkdir -p 噪鹛科/黑喉噪鹛
mkdir -p 噪鹛科/白颊噪鹛
mkdir -p 噪鹛科/黑脸噪鹛
mkdir -p 噪鹛科/黑领噪鹛
mkdir -p 噪鹛科/山噪鹛
mkdir -p 噪鹛科/矛纹草鹛
mkdir -p 噪鹛科/大草鹛
mkdir -p 噪鹛科/棕草鹛
mkdir -p 噪鹛科/白喉噪鹛
mkdir -p 噪鹛科/台湾白喉噪鹛
mkdir -p 噪鹛科/灰胁噪鹛
mkdir -p 噪鹛科/棕噪鹛
mkdir -p 噪鹛科/台湾棕噪鹛
mkdir -p 莺鹛科/黑顶林莺
mkdir -p 莺鹛科/横斑林莺
mkdir -p 莺鹛科/沙白喉林莺
mkdir -p 莺鹛科/白喉林莺
mkdir -p 莺鹛科/休氏白喉林莺
mkdir -p 莺鹛科/东歌林莺
mkdir -p 莺鹛科/亚洲漠地林莺
mkdir -p 莺鹛科/灰白喉林莺
mkdir -p 鸦雀科/火尾绿鹛
mkdir -p 鸦雀科/金胸雀鹛
mkdir -p 鸦雀科/宝兴鹛雀
mkdir -p 鸦雀科/白眉雀鹛
mkdir -p 鸦雀科/中华雀鹛
mkdir -p 鸦雀科/棕头雀鹛
mkdir -p 鸦雀科/中南雀鹛
mkdir -p 鸦雀科/路德雀鹛
mkdir -p 鸦雀科/灰头雀鹛
mkdir -p 鸦雀科/褐头雀鹛
mkdir -p 鸦雀科/玉山雀鹛
mkdir -p 鸦雀科/金眼鹛雀
mkdir -p 鸦雀科/山鹛
mkdir -p 鸦雀科/西域山鹛
mkdir -p 鸦雀科/红嘴鸦雀
mkdir -p 鸦雀科/三趾鸦雀
mkdir -p 鸦雀科/褐鸦雀
mkdir -p 鸦雀科/白眶鸦雀
mkdir -p 鸦雀科/棕头鸦雀
mkdir -p 鸦雀科/灰喉鸦雀
mkdir -p 鸦雀科/褐翅鸦雀
mkdir -p 鸦雀科/暗色鸦雀
mkdir -p 鸦雀科/灰冠鸦雀
mkdir -p 鸦雀科/黄额鸦雀
mkdir -p 鸦雀科/橙额鸦雀
mkdir -p 鸦雀科/金色鸦雀
mkdir -p 鸦雀科/短尾鸦雀
mkdir -p 鸦雀科/黑眉鸦雀
mkdir -p 鸦雀科/白胸鸦雀
mkdir -p 鸦雀科/红头鸦雀
mkdir -p 鸦雀科/灰头鸦雀
mkdir -p 鸦雀科/点胸鸦雀
mkdir -p 鸦雀科/震旦鸦雀
mkdir -p 绣眼鸟科/白领凤鹛
mkdir -p 绣眼鸟科/栗耳凤鹛
mkdir -p 绣眼鸟科/栗颈凤鹛
mkdir -p 绣眼鸟科/黑颏凤鹛
mkdir -p 绣眼鸟科/褐头凤鹛
mkdir -p 绣眼鸟科/黄颈凤鹛
mkdir -p 绣眼鸟科/白项凤鹛
mkdir -p 绣眼鸟科/纹喉凤鹛
mkdir -p 绣眼鸟科/棕臀凤鹛
mkdir -p 绣眼鸟科/红胁绣眼鸟
mkdir -p 绣眼鸟科/暗绿绣眼鸟
mkdir -p 绣眼鸟科/日本绣眼鸟
mkdir -p 绣眼鸟科/灰腹绣眼鸟
mkdir -p 绣眼鸟科/低地绣眼鸟
mkdir -p 和平鸟科/和平鸟
mkdir -p 戴菊科/台湾戴菊
mkdir -p 戴菊科/戴菊
mkdir -p 丽星鹩鹛科/丽星鹩鹛
mkdir -p 鹪鹩科/鹪鹩
mkdir -p 䴓科/普通䴓
mkdir -p 䴓科/栗臀䴓
mkdir -p 䴓科/栗腹䴓
mkdir -p 䴓科/白尾䴓
mkdir -p 䴓科/滇䴓
mkdir -p 䴓科/黑头䴓
mkdir -p 䴓科/白脸䴓
mkdir -p 䴓科/绒额䴓
mkdir -p 䴓科/淡紫䴓
mkdir -p 䴓科/巨䴓
mkdir -p 䴓科/丽䴓
mkdir -p 旋壁雀科/红翅旋壁雀
mkdir -p 旋木雀科/旋木雀
mkdir -p 旋木雀科/霍氏旋木雀
mkdir -p 旋木雀科/高山旋木雀
mkdir -p 旋木雀科/锈红腹旋木雀
mkdir -p 旋木雀科/褐喉旋木雀
mkdir -p 旋木雀科/休氏旋木雀
mkdir -p 旋木雀科/四川旋木雀
mkdir -p 椋鸟科/亚洲辉椋鸟
mkdir -p 椋鸟科/斑翅椋鸟
mkdir -p 椋鸟科/金冠树八哥
mkdir -p 椋鸟科/鹩哥
mkdir -p 椋鸟科/林八哥
mkdir -p 椋鸟科/八哥
mkdir -p 椋鸟科/白领八哥
mkdir -p 椋鸟科/家八哥
mkdir -p 椋鸟科/红嘴椋鸟
mkdir -p 椋鸟科/丝光椋鸟
mkdir -p 椋鸟科/灰椋鸟
mkdir -p 椋鸟科/黑领椋鸟
mkdir -p 椋鸟科/斑椋鸟
mkdir -p 椋鸟科/暹罗斑椋鸟
mkdir -p 椋鸟科/北椋鸟
mkdir -p 椋鸟科/紫背椋鸟
mkdir -p 椋鸟科/灰背椋鸟
mkdir -p 椋鸟科/灰头椋鸟
mkdir -p 椋鸟科/黑冠椋鸟
mkdir -p 椋鸟科/粉红椋鸟
mkdir -p 椋鸟科/紫翅椋鸟
mkdir -p 鸫科/蓝大翅鸲
mkdir -p 鸫科/紫宽嘴鸫
mkdir -p 鸫科/绿宽嘴鸫
mkdir -p 鸫科/长尾地鸫
mkdir -p 鸫科/淡背地鸫
mkdir -p 鸫科/喜山淡背地鸫
mkdir -p 鸫科/四川淡背地鸫
mkdir -p 鸫科/大长嘴地鸫
mkdir -p 鸫科/长嘴地鸫
mkdir -p 鸫科/虎斑地鸫
mkdir -p 鸫科/小虎斑地鸫
mkdir -p 鸫科/白眉地鸫
mkdir -p 鸫科/橙头地鸫
mkdir -p 鸫科/宝兴歌鸫
mkdir -p 鸫科/欧歌鸫
mkdir -p 鸫科/槲鸫
mkdir -p 鸫科/乌鸫
mkdir -p 鸫科/白眉歌鸫
mkdir -p 鸫科/欧乌鸫
mkdir -p 鸫科/白头鸫
mkdir -p 鸫科/灰翅鸫
mkdir -p 鸫科/蒂氏鸫
mkdir -p 鸫科/黑胸鸫
mkdir -p 鸫科/乌灰鸫
mkdir -p 鸫科/灰背鸫
mkdir -p 鸫科/白眉鸫
mkdir -p 鸫科/白腹鸫
mkdir -p 鸫科/褐头鸫
mkdir -p 鸫科/赤胸鸫
mkdir -p 鸫科/藏乌鸫
mkdir -p 鸫科/棕背黑头鸫
mkdir -p 鸫科/田鸫
mkdir -p 鸫科/黑喉鸫
mkdir -p 鸫科/赤颈鸫
mkdir -p 鸫科/斑鸫
mkdir -p 鸫科/红尾斑鸫
mkdir -p 鸫科/灰头鸫
mkdir -p 鸫科/白颈鸫
mkdir -p 鹟科/棕薮鸲
mkdir -p 鹟科/鹊鸲
mkdir -p 鹟科/白腰鹊鸲
mkdir -p 鹟科/斑鹟
mkdir -p 鹟科/灰纹鹟
mkdir -p 鹟科/乌鹟
mkdir -p 鹟科/北灰鹟
mkdir -p 鹟科/褐胸鹟
mkdir -p 鹟科/棕尾褐鹟
mkdir -p 鹟科/白喉姬鹟
mkdir -p 鹟科/海南蓝仙鹟
mkdir -p 鹟科/纯蓝仙鹟
mkdir -p 鹟科/灰颊仙鹟
mkdir -p 鹟科/山蓝仙鹟
mkdir -p 鹟科/大蓝仙鹟
mkdir -p 鹟科/蓝喉仙鹟
mkdir -p 鹟科/中华仙鹟
mkdir -p 鹟科/白喉林鹟
mkdir -p 鹟科/白尾蓝仙鹟
mkdir -p 鹟科/棕腹大仙鹟
mkdir -p 鹟科/棕腹仙鹟
mkdir -p 鹟科/棕腹蓝仙鹟
mkdir -p 鹟科/大仙鹟
mkdir -p 鹟科/小仙鹟
mkdir -p 鹟科/白腹蓝鹟
mkdir -p 鹟科/琉璃蓝鹟
mkdir -p 鹟科/铜蓝鹟
mkdir -p 鹟科/欧亚鸲
mkdir -p 鹟科/栗背短翅鸫
mkdir -p 鹟科/锈腹短翅鸫
mkdir -p 鹟科/白喉短翅鸫
mkdir -p 鹟科/喜山短翅鸫
mkdir -p 鹟科/中华短翅鸫
mkdir -p 鹟科/台湾短翅鸫
mkdir -p 鹟科/栗腹歌鸲
mkdir -p 鹟科/蓝歌鸲
mkdir -p 鹟科/红尾歌鸲
mkdir -p 鹟科/棕头歌鸲
mkdir -p 鹟科/琉球歌鸲
mkdir -p 鹟科/日本歌鸲
mkdir -p 鹟科/蓝喉歌鸲
mkdir -p 鹟科/白腹短翅鸲
mkdir -p 鹟科/新疆歌鸲
mkdir -p 鹟科/黑胸歌鸲
mkdir -p 鹟科/白须黑胸歌鸲
mkdir -p 鹟科/红喉歌鸲
mkdir -p 鹟科/金胸歌鸲
mkdir -p 鹟科/黑喉歌鸲
mkdir -p 鹟科/白尾蓝地鸲
mkdir -p 鹟科/白眉林鸲
mkdir -p 鹟科/台湾白眉林鸲
mkdir -p 鹟科/棕腹林鸲
mkdir -p 鹟科/台湾林鸲
mkdir -p 鹟科/红胁蓝尾鸲
mkdir -p 鹟科/蓝眉林鸲
mkdir -p 鹟科/祁连山蓝尾鸲
mkdir -p 鹟科/金色林鸲
mkdir -p 鹟科/小燕尾
mkdir -p 鹟科/黑背燕尾
mkdir -p 鹟科/灰背燕尾
mkdir -p 鹟科/白冠燕尾
mkdir -p 鹟科/斑背燕尾
mkdir -p 鹟科/台湾紫啸鸫
mkdir -p 鹟科/紫啸鸫
mkdir -p 鹟科/蓝额长脚地鸲
mkdir -p 鹟科/白眉姬鹟
mkdir -p 鹟科/绿背姬鹟
mkdir -p 鹟科/黄眉姬鹟
mkdir -p 鹟科/琉球姬鹟
mkdir -p 鹟科/锈胸蓝姬鹟
mkdir -p 鹟科/鸲姬鹟
mkdir -p 鹟科/侏蓝姬鹟
mkdir -p 鹟科/橙胸姬鹟
mkdir -p 鹟科/玉头姬鹟
mkdir -p 鹟科/白眉蓝姬鹟
mkdir -p 鹟科/小斑姬鹟
mkdir -p 鹟科/灰蓝姬鹟
mkdir -p 鹟科/棕胸蓝姬鹟
mkdir -p 鹟科/栗尾姬鹟
mkdir -p 鹟科/红喉姬鹟
mkdir -p 鹟科/红胸姬鹟
mkdir -p 鹟科/斑姬鹟
mkdir -p 鹟科/贺兰山红尾鸲
mkdir -p 鹟科/红背红尾鸲
mkdir -p 鹟科/蓝头红尾鸲
mkdir -p 鹟科/赭红尾鸲
mkdir -p 鹟科/欧亚红尾鸲
mkdir -p 鹟科/黑喉红尾鸲
mkdir -p 鹟科/白喉红尾鸲
mkdir -p 鹟科/北红尾鸲
mkdir -p 鹟科/红腹红尾鸲
mkdir -p 鹟科/蓝额红尾鸲
mkdir -p 鹟科/红尾水鸲
mkdir -p 鹟科/白顶溪鸲
mkdir -p 鹟科/白背矶鸫
mkdir -p 鹟科/蓝矶鸫
mkdir -p 鹟科/栗腹矶鸫
mkdir -p 鹟科/白喉矶鸫
mkdir -p 鹟科/白喉石䳭
mkdir -p 鹟科/黑喉石䳭
mkdir -p 鹟科/东亚石䳭
mkdir -p 鹟科/白斑黑石䳭
mkdir -p 鹟科/黑白林䳭
mkdir -p 鹟科/灰林䳭
mkdir -p 鹟科/穗䳭
mkdir -p 鹟科/沙䳭
mkdir -p 鹟科/漠䳭
mkdir -p 鹟科/白顶䳭
mkdir -p 鹟科/东方斑䳭
mkdir -p 河乌科/河乌
mkdir -p 河乌科/褐河乌
mkdir -p 叶鹎科/蓝翅叶鹎
mkdir -p 叶鹎科/金额叶鹎
mkdir -p 叶鹎科/黄冠橙腹叶鹎
mkdir -p 叶鹎科/橙腹叶鹎
mkdir -p 啄花鸟科/厚嘴啄花鸟
mkdir -p 啄花鸟科/黄臀啄花鸟
mkdir -p 啄花鸟科/黄腹啄花鸟
mkdir -p 啄花鸟科/纯色啄花鸟
mkdir -p 啄花鸟科/红胸啄花鸟
mkdir -p 啄花鸟科/朱背啄花鸟
mkdir -p 太阳鸟科/紫颊直嘴太阳鸟
mkdir -p 太阳鸟科/褐喉食蜜鸟
mkdir -p 太阳鸟科/紫色花蜜鸟
mkdir -p 太阳鸟科/黄腹花蜜鸟
mkdir -p 太阳鸟科/蓝喉太阳鸟
mkdir -p 太阳鸟科/绿喉太阳鸟
mkdir -p 太阳鸟科/叉尾太阳鸟
mkdir -p 太阳鸟科/黑胸太阳鸟
mkdir -p 太阳鸟科/黄腰太阳鸟
mkdir -p 太阳鸟科/火尾太阳鸟
mkdir -p 太阳鸟科/蓝枕花蜜鸟
mkdir -p 太阳鸟科/长嘴捕蛛鸟
mkdir -p 太阳鸟科/纹背捕蛛鸟
mkdir -p 雀科/石雀
mkdir -p 雀科/白腰雪雀
mkdir -p 雀科/藏雪雀
mkdir -p 雀科/白斑翅雪雀
mkdir -p 雀科/褐翅雪雀
mkdir -p 雀科/棕颈雪雀
mkdir -p 雀科/黑喉雪雀
mkdir -p 雀科/棕背雪雀
mkdir -p 雀科/山麻雀
mkdir -p 雀科/麻雀
mkdir -p 雀科/黑顶麻雀
mkdir -p 雀科/黑胸麻雀
mkdir -p 雀科/家麻雀
mkdir -p 织雀科/纹胸织雀
mkdir -p 织雀科/黄胸织雀
mkdir -p 梅花雀科/斑文鸟
mkdir -p 梅花雀科/白腰文鸟
mkdir -p 梅花雀科/栗腹文鸟
mkdir -p 梅花雀科/长尾鹦雀
mkdir -p 梅花雀科/红梅花雀
mkdir -p 岩鹨科/领岩鹨
mkdir -p 岩鹨科/高原岩鹨
mkdir -p 岩鹨科/鸲岩鹨
mkdir -p 岩鹨科/棕胸岩鹨
mkdir -p 岩鹨科/棕眉山岩鹨
mkdir -p 岩鹨科/褐岩鹨
mkdir -p 岩鹨科/黑喉岩鹨
mkdir -p 岩鹨科/贺兰山岩鹨
mkdir -p 岩鹨科/栗背岩鹨
mkdir -p 鹡鸰科/山鹡鸰
mkdir -p 鹡鸰科/西黄鹡鸰
mkdir -p 鹡鸰科/黄鹡鸰
mkdir -p 鹡鸰科/黄头鹡鸰
mkdir -p 鹡鸰科/灰鹡鸰
mkdir -p 鹡鸰科/白鹡鸰
mkdir -p 鹡鸰科/日本鹡鸰
mkdir -p 鹡鸰科/大斑鹡鸰
mkdir -p 鹡鸰科/理氏鹨
mkdir -p 鹡鸰科/田鹨
mkdir -p 鹡鸰科/布氏鹨
mkdir -p 鹡鸰科/平原鹨
mkdir -p 鹡鸰科/草地鹨
mkdir -p 鹡鸰科/林鹨
mkdir -p 鹡鸰科/树鹨
mkdir -p 鹡鸰科/北鹨
mkdir -p 鹡鸰科/粉红胸鹨
mkdir -p 鹡鸰科/红喉鹨
mkdir -p 鹡鸰科/黄腹鹨
mkdir -p 鹡鸰科/水鹨
mkdir -p 鹡鸰科/山鹨
mkdir -p 朱鹀科/朱鹀
mkdir -p 燕雀科/苍头燕雀
mkdir -p 燕雀科/燕雀
mkdir -p 燕雀科/黄颈拟蜡嘴雀
mkdir -p 燕雀科/白点翅拟蜡嘴雀
mkdir -p 燕雀科/白斑翅拟蜡嘴雀
mkdir -p 燕雀科/锡嘴雀
mkdir -p 燕雀科/黑尾蜡嘴雀
mkdir -p 燕雀科/黑头蜡嘴雀
mkdir -p 燕雀科/松雀
mkdir -p 燕雀科/褐灰雀
mkdir -p 燕雀科/红头灰雀
mkdir -p 燕雀科/灰头灰雀
mkdir -p 燕雀科/台湾灰头灰雀
mkdir -p 燕雀科/红腹灰雀
mkdir -p 燕雀科/红翅沙雀
mkdir -p 燕雀科/蒙古沙雀
mkdir -p 燕雀科/赤朱雀
mkdir -p 燕雀科/红眉金翅雀
mkdir -p 燕雀科/金枕黑雀
mkdir -p 燕雀科/暗胸朱雀
mkdir -p 燕雀科/林岭雀
mkdir -p 燕雀科/高山岭雀
mkdir -p 燕雀科/粉红腹岭雀
mkdir -p 燕雀科/普通朱雀
mkdir -p 燕雀科/血雀
mkdir -p 燕雀科/拟大朱雀
mkdir -p 燕雀科/大朱雀
mkdir -p 燕雀科/喜山红腰朱雀
mkdir -p 燕雀科/红腰朱雀
mkdir -p 燕雀科/红眉朱雀
mkdir -p 燕雀科/中华朱雀
mkdir -p 燕雀科/曙红朱雀
mkdir -p 燕雀科/玫红眉朱雀
mkdir -p 燕雀科/棕朱雀
mkdir -p 燕雀科/喜山点翅朱雀
mkdir -p 燕雀科/点翅朱雀
mkdir -p 燕雀科/酒红朱雀
mkdir -p 燕雀科/台湾酒红朱雀
mkdir -p 燕雀科/沙色朱雀
mkdir -p 燕雀科/藏雀
mkdir -p 燕雀科/褐头朱雀
mkdir -p 燕雀科/长尾雀
mkdir -p 燕雀科/中华长尾雀
mkdir -p 燕雀科/北朱雀
mkdir -p 燕雀科/斑翅朱雀
mkdir -p 燕雀科/喜山白眉朱雀
mkdir -p 燕雀科/白眉朱雀
mkdir -p 燕雀科/红胸朱雀
mkdir -p 燕雀科/红眉松雀
mkdir -p 燕雀科/欧金翅雀
mkdir -p 燕雀科/金翅雀
mkdir -p 燕雀科/高山金翅雀
mkdir -p 燕雀科/黑头金翅雀
mkdir -p 燕雀科/巨嘴沙雀
mkdir -p 燕雀科/黄嘴朱顶雀
mkdir -p 燕雀科/赤胸朱顶雀
mkdir -p 燕雀科/白腰朱顶雀
mkdir -p 燕雀科/极北朱顶雀
mkdir -p 燕雀科/红交嘴雀
mkdir -p 燕雀科/白翅交嘴雀
mkdir -p 燕雀科/红额金翅雀
mkdir -p 燕雀科/金额丝雀
mkdir -p 燕雀科/藏黄雀
mkdir -p 燕雀科/黄雀
mkdir -p 铁爪鹀科/铁爪鹀
mkdir -p 铁爪鹀科/雪鹀
mkdir -p 鹀科/凤头鹀
mkdir -p 鹀科/蓝鹀
mkdir -p 鹀科/黍鹀
mkdir -p 鹀科/黄鹀
mkdir -p 鹀科/白头鹀
mkdir -p 鹀科/淡灰眉岩鹀
mkdir -p 鹀科/灰眉岩鹀
mkdir -p 鹀科/三道眉草鹀
mkdir -p 鹀科/白顶鹀
mkdir -p 鹀科/栗斑腹鹀
mkdir -p 鹀科/灰颈鹀
mkdir -p 鹀科/圃鹀
mkdir -p 鹀科/白眉鹀
mkdir -p 鹀科/栗耳鹀
mkdir -p 鹀科/小鹀
mkdir -p 鹀科/黄眉鹀
mkdir -p 鹀科/田鹀
mkdir -p 鹀科/黄喉鹀
mkdir -p 鹀科/黄胸鹀
mkdir -p 鹀科/栗鹀
mkdir -p 鹀科/藏鹀
mkdir -p 鹀科/黑头鹀
mkdir -p 鹀科/褐头鹀
mkdir -p 鹀科/硫黄鹀
mkdir -p 鹀科/灰头鹀
mkdir -p 鹀科/日本灰头鹀
mkdir -p 鹀科/灰鹀
mkdir -p 鹀科/苇鹀
mkdir -p 鹀科/红颈苇鹀
mkdir -p 鹀科/芦鹀
mkdir -p 雀鹀科/白冠带鹀
mkdir -p 雀鹀科/稀树草鹀
